import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "menu.home": "Home",
    "menu.dashboard": "Dashboard",
    "menu.courses": "Courses",
    "menu.my_courses": "My Courses",
    "menu.students": "Students",
    "menu.student_management": "Student Management",
    "menu.attendance": "Attendance",
    "menu.user_management": "User Management",
    "menu.learning_materials": "Learning Materials",
    "menu.reports": "Reports",
    "menu.settings": "Settings",
    "menu.learning_path": "Learning Path",
    "menu.ai_learning": "AI Learning",
    "menu.flashcards": "Flashcards",
    "menu.achievements": "Achievements",
    "menu.english_games": "English Games",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.actions": "Actions",
    "common.loading": "Loading...",
    "common.no_data": "No data found",
    "attendance.course_label": "Course",
    "search.placeholder": "Search...",
    "header.logout": "Logout",
    "learning_path.subtitle": "Continue your lessons and track your progress",
    "learning_path.unit1": "Unit 1: Greetings & Introductions",
    "learning_path.unit2": "Unit 2: Family & Friends",
    "learning_path.unit3": "Unit 3: Daily Conversations",
    "learning_path.unit4": "Unit 4: Hobbies & Activities",
    "learning_path.unit5": "Unit 5: Food & Restaurants",
    "learning_path.unit6": "Unit 6: Travel & Places",
    "learning_path.in_progress": "In Progress",
    "learning_path.completed": "Completed",
    "learning_path.not_started": "Not Started",
    "learning_path.progress": "Progress",
    "learning_path.learn_now": "Learn Now",
    "learning_path.materials": "Materials",
    "learning_path.flashcards": "Flashcards",
    "learning_path.speaking": "Speaking",
    "learning_path.review": "Review",
    "learning_path.locked": "Locked",
    "dashboard.welcome": "Welcome back, Minh Duc",
    "dashboard.subtitle": "Here's what you need to do today",
    "dashboard.streak_message": "Keep your streak going and complete your daily missions",
    "dashboard.learning_streak": "Learning Streak",
    "dashboard.7_days": "7 Days",
    "dashboard.studied_7_days": "You've studied 7 days in a row",
    "dashboard.view_calendar": "View Calendar",
    "dashboard.homework": "Homework",
    "dashboard.tasks_remaining": "2 tasks remaining",
    "dashboard.next_deadline": "Next deadline:",
    "dashboard.continue": "Continue",
    "dashboard.ai_speaking": "AI Speaking Practice",
    "dashboard.practice_now": "Practice Now",
    "dashboard.current_rank": "Current Rank",
    "dashboard.in_your_class": "in your class",
    "dashboard.view_leaderboard": "View Leaderboard",
    "dashboard.todays_classes": "Today's Classes",
    "dashboard.schedule_date": "Your schedule for Thursday, March 26, 2026",
    "dashboard.now": "Now",
    "dashboard.english": "English Language",
    "dashboard.ms_thuthao": "Ms. Thu Thao • Room 5A",
    "dashboard.in_progress": "In Progress",
    "dashboard.todays_topic": "Today's Topic",
    "dashboard.topic_en": "Unit 3: Daily Conversations - Practice Dialogues",
    "dashboard.join_class": "Join Class",
    "dashboard.view_materials": "View Materials",
    "dashboard.next": "Next",
    "dashboard.math": "Mathematics",
    "dashboard.mr_hoangnam": "Mr. Hoang Nam • Room 5A",
    "dashboard.starts_15": "Starts in 15 min",
    "dashboard.topic_math": "Chapter 5: Fractions - Adding & Subtracting",
    "dashboard.later": "Later",
    "dashboard.science": "Science",
    "dashboard.ms_lananh": "Ms. Lan Anh • Science Lab",
    "dashboard.after_lunch": "After lunch",
    "dashboard.topic_sci": "Biology: Plant Life Cycles - Lab Activity",
    "dashboard.my_rank": "My Rank",
    "dashboard.see_who": "See who is just above and below you",
    "dashboard.you": "Minh Duc (You)",
    "dashboard.todays_goals": "Today's Goals",
    "dashboard.goal1": "Finish homework",
    "dashboard.goal2": "Practice AI speaking for 10 minutes",
    "dashboard.goal2_status": "5/10 minutes completed",
    "dashboard.goal3": "Review 15 flashcards",
    "dashboard.teacher_dashboard": "Teacher Dashboard",
    "dashboard.your_schedule": "Your schedule for today",
    "dashboard.view_full_schedule": "View Full Schedule",
    "dashboard.absent_today": "Absent Today",
    "dashboard.late_arrivals": "Late Arrivals Today",
    "dashboard.parent_contacted": "Parent Contacted",
    "dashboard.contact_required": "Contact Required",
    "dashboard.total_materials_desc": "Total uploaded content",
    "dashboard.upload_new": "Upload New",
    "dashboard.minutes_late": "min late",
    "dashboard.upcoming": "Upcoming",
    "dashboard.view_details": "View Details",
    "course.start_time": "Start Time",
    "course.end_time": "End Time",
    "auth.welcome": "Welcome Back",
    "auth.login_subtitle": "Sign in to access your EduLMS workspace",
    "auth.username": "Username",
    "auth.password": "Password",
    "auth.remember": "Remember me",
    "auth.forgot": "Forgot your password?",
    "auth.signin": "Sign In",
    "auth.new_to": "New to EduLMS?",
    "auth.create_account": "Create an account",
    "auth.create_title": "Create your account",
    "auth.join_subtitle": "Join EduLMS and experience smart learning",
    "auth.firstname": "First name",
    "auth.lastname": "Last name",
    "auth.email": "Email address",
    "auth.registering": "Registration Successful!",
    "auth.redirecting": "Redirecting to login...",
    "auth.already_have": "Already have an account?",
    "auth.signin_to": "Sign in to your account",
    "Create System Account": "Create System Account",
    "Create Student Account": "Create Student Account",
    // ── Course Management ──
    "course.page_title": "Course Management",
    "course.page_subtitle": "Create, manage and organize your courses",
    "course.add_btn": "Add Course",
    "course.add_lesson": "Add Lesson",
    "course.add_title": "Create New Course",
    "course.add_subtitle": "Fill in the details to create a new course",
    "course.edit_title": "Edit Course",
    "course.edit_subtitle": "Update course information",
    "course.name": "Course Name",
    "course.name_placeholder": "e.g. IELTS Foundation",
    "course.code": "Course Code",
    "course.code_placeholder": "e.g. IELTS-001",
    "course.level": "Level",
    "course.start_date": "Start Date",
    "course.end_date": "End Date",
    "course.study_schedule": "Study Schedule",
    "course.schedule_placeholder": "e.g. Mon, Wed, Fri 18:00-20:00",
    "course.max_attendants": "Max Attendants",
    "course.description": "Description",
    "course.description_placeholder": "Enter course description...",
    "course.status": "Status",
    "course.cancel": "Cancel",
    "course.create_btn": "Create Course",
    "course.save_btn": "Save Changes",
    "course.delete_btn": "Delete",
    "course.assign_students": "Assign Students",
    "course.assign_teachers": "Assign Teachers",
    "course.delete_title": "Delete Course",
    "course.delete_warning": "This action cannot be undone",
    "course.delete_confirm": "Are you sure you want to delete",
    "course.total_courses": "Total Courses",
    "course.active_courses": "Active Courses",
    "course.draft_courses": "Draft Courses",
    "course.search_placeholder": "Search by name or course code...",
    "course.no_courses": "No courses found",
    "course.no_courses_hint": "Click 'Add Course' to create your first course",
    "course.col_name": "Course Name",
    "course.col_code": "Code",
    "course.col_level": "Level",
    "course.col_schedule": "Schedule",
    "course.col_dates": "Duration",
    "course.col_capacity": "Capacity",
    "course.col_status": "Status",
    "course.col_actions": "Actions",
    "course.created_success": "Course created successfully!",
    "course.updated_success": "Course updated successfully!",
    "course.deleted_success": "Course deleted successfully!",
    "course.save_error": "Failed to save course. Please try again.",
    "course.delete_error": "Failed to delete course. Please try again.",
    "course.error_name_required": "Course name is required",
    "course.error_code_required": "Course code is required",
    "course.error_start_required": "Start date is required",
    "course.error_end_required": "End date is required",
    "course.error_end_after_start": "End date must be after start date",
    "course.error_schedule_required": "Study schedule is required",
    "course.error_attendants_range": "Attendants must be between 1 and 500",
    "course.error_teacher_required_for_active": "Teacher must be assigned before activating the course",
    "course.exam_zone": "Exam & Test Zone",
    "course.exam_zone_desc": "Assessments and proficiency checks",
    "course.create_test": "Create Test",
    "course.manage_test": "Manage Test",
    "course.do_test": "Do Test",
    "course.no_exams": "No exams scheduled for this course yet.",
    "test.title": "Exam Title",
    "test.time_limit": "Time Limit (Minutes)",
    "test.pass_score": "Passing Score (%)",
    "test.total_score": "Total Score",
    "test.description": "Description (Optional)",
    "test.questions": "Questions",
    "test.add_question": "Add Question",
    "attendance.manage_title": "Attendance Management",
    "attendance.manage_subtitle": "Manage and track student attendance records",
    "attendance.class_label": "Class:",
    "attendance.total_students": "Total Students",
    "attendance.present": "Present",
    "attendance.absent": "Absent",
    "attendance.late": "Late",
    "attendance.import_title": "Import Attendance from Excel",
    "attendance.import_subtitle": "Upload an Excel file with student attendance information",
    "attendance.export_template": "Export Template",
    "attendance.drag_drop": "Drag and drop your Excel file here or click to browse",
    "attendance.supported_formats": "Supported formats: .xlsx, .xls • Max size: 5MB",
    "attendance.import_btn": "Import File",
    "attendance.direct_title": "Direct Attendance Checklist",
    "attendance.search_placeholder": "Search by name or ID...",
    "attendance.status_all": "All Status",
    "attendance.status_present": "Present",
    "attendance.status_absent": "Absent",
    "attendance.status_late": "Late",
    "attendance.col_avatar": "Avatar",
    "attendance.col_id": "Student ID",
    "attendance.col_name": "Full Name",
    "attendance.col_status": "Status",
    "attendance.reset": "Reset",
    "attendance.save": "Save Attendance",
    "attendance.success_import": "Attendance imported successfully!",
    "attendance.success_save": "Attendance saved successfully!",
    "attendance.error": "An error occurred while processing attendance.",
    "attendance.history_title": "Attendance History",
    "attendance.history_subtitle": "Track student attendance and patterns",
    "attendance.todays_attendance": "Latest Attendance",
    "attendance.present_students": "Present Students",
    "attendance.absent_students": "Absent Students",
    "attendance.col_date": "Date",
    "attendance.col_class": "Course",
    "attendance.col_present": "Present",
    "attendance.col_absent": "Absent",
    "attendance.col_total": "Total",
    "attendance.col_percentage": "Percentage",
    "attendance.select_course": "Select Course",
    "attendance.export_monthly": "Export Monthly Report",
    "My Courses": "My Courses",
    "Track your progress across all subjects": "Track your progress across all subjects",
    "Instructor": "Instructor",
    "lessons completed": "lessons completed",
    "Next": "Next",
    "Course completed! Well done!": "Course completed! Well done!",
    "Review Course": "Review Course",
    "View Certificate": "View Certificate",
    "Continue Learning": "Continue Learning",
    "Course Details": "Course Details",
    "materials.page_title": "Learning Materials",
    "materials.page_subtitle": "Upload, create, and manage course learning resources",
    "materials.total_materials": "Total Materials",
    "materials.pdf_images": "PDF & Images",
    "materials.flashcards": "Flashcards",
    "materials.games": "English Games",
    "materials.upload_title": "Upload Files",
    "materials.drop_hint": "Drop files here or click to upload",
    "materials.supported_formats": "Supported formats: PDF, PNG, JPG, JPEG, DOC, DOCX, PPT, PPTX (Max 50MB)",
    "materials.create_content": "Create Learning Content",
    "materials.create_material": "Create Course Material",
    "materials.create_material_desc": "Create PDF, documents, or presentations for courses",
    "materials.create_game": "Create English Game",
    "materials.create_game_desc": "Design interactive games for English learning",
    "materials.create_flashcards_desc": "Build flashcard sets for vocabulary practice",
    "materials.library_title": "Material Library",
    "materials.library_subtitle": "Manage all your learning materials",
    "materials.search_placeholder": "Search materials...",
    "materials.col_name": "Material Name",
    "materials.col_type": "Type",
    "materials.col_course": "Course",
    "materials.col_created_by": "Created By",
    "materials.col_last_updated": "Last Updated",
    "materials.col_status": "Status",
    "materials.col_downloads": "Downloads",
    "materials.col_actions": "Actions",
    "materials.upload_success": "Uploaded successfully!",
    "materials.delete_success": "Material deleted successfully!",
    "materials.upload_confirm": "Are you sure you want to upload these files?",
    "materials.delete_confirm": "Are you sure you want to delete this material?",
    "materials.no_materials": "No materials found",
    "materials.category": "Category",
    "materials.general": "General",
    "materials.flashcard": "Flashcard",
    "materials.game": "English Game",
    "materials.preview_mode": "Preview Mode",
    "materials.preview_unavailable": "Preview not available",
    "materials.preview_unavailable_desc": "This file type cannot be previewed in the browser. Please download it to view the content.",
    "materials.all_types": "All Types",
    "materials.all_status": "All Status",
    "materials.published": "Published",
    "materials.draft": "Draft",
    "flashcard.review_subtitle": "Review vocabulary and play learning games",
    "flashcard.card": "Card",
    "flashcard.complete": "Complete",
    "flashcard.flip": "Flip Card",
    "flashcard.no_data": "No flashcards available yet.",
    "games.title": "Learning Games",
    "games.match_title": "Match the Word",
    "games.match_desc": "Match words with their meanings",
    "games.image_title": "Choose the Image",
    "games.image_desc": "Pick the correct image for each word",
    "games.spell_title": "Spell the Word",
    "games.spell_desc": "Test your spelling skills",
    "flashcard.management_title": "Vocabularies",
    "flashcard.management_subtitle": "Manage your vocabulary flashcards and IPA guides",
    "flashcard.add_btn": "Add Vocabulary",
    "flashcard.edit_btn": "Edit Vocabulary",
    "flashcard.total_words": "Total Words",
    "flashcard.word": "Word",
    "flashcard.ipa": "IPA (Phonetic)",
    "flashcard.definition": "Definition",
    "flashcard.example": "Example Sentence",
    "flashcard.created_success": "Vocabulary saved successfully!",
    "flashcard.deleted_success": "Vocabulary deleted successfully!",
    "flashcard.delete_confirm": "Are you sure you want to delete this vocabulary?",
    "flashcard.topic": "Topic",
    "flashcard.topic_placeholder": "e.g. Animals, Food...",
    "flashcard.image": "Image (Optional)",
    "flashcard.upload_image": "Upload Image",
    "flashcard.image_url_placeholder": "Or paste an image URL here...",
    "flashcard.uploading": "Uploading...",
    "flashcard.all_topics": "All Topics",
    "flashcard.sync_ai": "Sync to AI",
    "flashcard.syncing_ai": "Syncing...",
    "flashcard.sync_success": "Synced vocabularies to AI Service successfully",
    "flashcard.sync_error": "Failed to sync vocabularies to AI",
    "games.scramble_title": "Word Scramble",
    "games.scramble_difficulty": "Easy",
    "games.scramble_desc": "Unscramble the letters to find the correct vocabulary word. Great for spelling practice!",
    "games.sentence_title": "Sentence Master",
    "games.sentence_desc": "Arrange the mixed-up words into a perfect sentence. Challenging and fun grammar practice!",
    "games.memory_title": "Memory Match",
    "games.memory_desc": "Flip cards to find pairs of words and their corresponding definitions or images.",
    "games.listen_title": "Listen & Type",
    "games.listen_desc": "Listen to the word's pronunciation and type it correctly with its IPA.",
    "games.translation_title": "Translation Master",
    "games.translation_desc": "Choose the correct translation for the given word. Test your vocabulary in both English and Vietnamese!",
    "games.translation_difficulty": "Medium",
    "games.translate_to_vn": "Translate to Vietnamese",
    "games.translate_to_en": "Translate to English",
    "games.play_now": "Play Now",
    "games.coming_soon": "Coming Soon",
    "games.back": "Back to Games",
    "games.scrambled_word": "Scrambled Word",
    "games.hint_label": "HINT / MEANING",
    "games.input_placeholder": "Type your answer here...",
    "games.verify_btn": "Verify Answer",
    "games.correct": "Correct!",
    "games.wrong": "Incorrect, try again!",
    "games.congrats": "Congratulations! You completed the game!",
    "games.roadmap_step1_title": "Fetch Content",
    "games.roadmap_step1_desc": "Uses the new /api/games/scramble endpoint to get dynamic challenges.",
    "games.roadmap_step2_title": "Live Verification",
    "games.roadmap_step2_desc": "Submit answers to /scramble/verify for instant server-side checking.",
    "games.roadmap_step3_title": "Future Rewards",
    "games.roadmap_step3_desc": "Coming soon: Earn coins and XP to unlock exclusive achievements!",
    "games.daily_title": "Daily Secret Challenge",
    "games.daily_subtitle": "A mysterious challenge awaits...",
    "games.daily_desc": "Complete today's secret quest to unlock bonus coins and XP. New challenge every 24 hours!",
    "games.daily_claimed": "Challenge Completed",
    "games.daily_difficulty": "SECRET",
    "games.rewards_title": "Rewards Earned",
    "games.xp": "XP",
    "games.coins": "Coins",
    "video.interactive_question": "Knowledge Check",
    "video.type_answer": "Type your answer...",
    "video.correct": "Correct! Well done.",
    "video.incorrect": "Incorrect. Try again!",
    "video.submit": "Submit Answer",
    "video.continue": "Continue Video",
    "video.tab": "Interactive Video",
    "ai_learning.title": "AI Learning Hub",
    "ai_learning.subtitle": "Choose a module to practice your English skills",
    "ai_learning.speaking": "Speaking Practice",
    "ai_learning.speaking_desc": "Practice conversational English with AI",
    "ai_learning.writing": "Writing Practice",
    "ai_learning.writing_desc": "Improve your writing skills and grammar",
    "ai_learning.choose_friend": "Choose your AI Friend",
    "ai_learning.start": "Start Practice",
  },

  vi: {
    "menu.home": "Trang chủ",
    "menu.dashboard": "Bảng điều khiển",
    "menu.courses": "Khóa học",
    "menu.my_courses": "Khóa học của tôi",
    "menu.students": "Học sinh",
    "menu.student_management": "Quản lý học sinh",
    "menu.attendance": "Điểm danh",
    "menu.user_management": "Quản lý người dùng",
    "menu.learning_materials": "Tài liệu học tập",
    "menu.reports": "Báo cáo",
    "menu.settings": "Cài đặt",
    "menu.learning_path": "Lộ trình học tập",
    "menu.ai_learning": "Học cùng AI",
    "menu.flashcards": "Thẻ ghi nhớ",
    "menu.achievements": "Thành tích",
    "menu.english_games": "Trò chơi tiếng Anh",
    "common.save": "Lưu",
    "common.cancel": "Hủy",
    "common.actions": "Thao tác",
    "common.loading": "Đang tải...",
    "common.no_data": "Không tìm thấy dữ liệu",
    "attendance.course_label": "Khoá học",
    "attendance.manage_title": "Quản lý điểm danh",
    "attendance.manage_subtitle": "Quản lý và theo dõi hồ sơ điểm danh của học sinh",
    "attendance.class_label": "Lớp:",
    "attendance.total_students": "Tổng số học sinh",
    "attendance.present": "Có mặt",
    "attendance.absent": "Vắng mặt",
    "attendance.late": "Muộn",
    "attendance.import_title": "Nhập điểm danh từ Excel",
    "attendance.import_subtitle": "Tải lên tệp Excel chứa thông tin điểm danh của học sinh",
    "attendance.export_template": "Xuất tệp mẫu",
    "attendance.drag_drop": "Kéo thả tệp Excel vào đây hoặc nhấp để chọn tệp",
    "attendance.supported_formats": "Định dạng hỗ trợ: .xlsx, .xls • Dung lượng tối đa: 5MB",
    "attendance.import_btn": "Nhập tệp",
    "attendance.direct_title": "Bảng điểm danh trực tiếp",
    "attendance.search_placeholder": "Tìm theo tên hoặc ID...",
    "attendance.status_all": "Tất cả trạng thái",
    "attendance.status_present": "Có mặt",
    "attendance.status_absent": "Vắng mặt",
    "attendance.status_late": "Muộn",
    "attendance.col_avatar": "Ảnh đại diện",
    "attendance.col_id": "Mã học sinh",
    "attendance.col_name": "Họ và tên",
    "attendance.col_status": "Trạng thái",
    "attendance.reset": "Đặt lại",
    "attendance.save": "Lưu điểm danh",
    "attendance.success_import": "Nhập điểm danh thành công!",
    "attendance.success_save": "Lưu điểm danh thành công!",
    "attendance.error": "Đã xảy ra lỗi khi xử lý điểm danh.",
    "attendance.history_title": "Lịch sử điểm danh",
    "attendance.history_subtitle": "Theo dõi việc điểm danh và xu hướng của học sinh",
    "attendance.todays_attendance": "Điểm danh gần nhất",
    "attendance.present_students": "Học sinh có mặt",
    "attendance.absent_students": "Học sinh vắng mặt",
    "attendance.col_date": "Ngày",
    "attendance.col_class": "Khóa học",
    "attendance.col_present": "Có mặt",
    "attendance.col_absent": "Vắng mặt",
    "attendance.col_total": "Tổng số",
    "attendance.col_percentage": "Tỷ lệ",
    "attendance.select_course": "Chọn khóa học",
    "attendance.export_monthly": "Xuất báo cáo tháng",

    "search.placeholder": "Tìm kiếm...",
    "header.logout": "Đăng xuất",
    "learning_path.subtitle": "Tiếp tục bài học và theo dõi tiến độ của bạn",
    "learning_path.unit1": "Bài 1: Chào hỏi & Giới thiệu",
    "learning_path.unit2": "Bài 2: Gia đình & Bạn bè",
    "learning_path.unit3": "Bài 3: Hội thoại hàng ngày",
    "learning_path.unit4": "Bài 4: Sở thích & Hoạt động",
    "learning_path.unit5": "Bài 5: Ẩm thực & Nhà hàng",
    "learning_path.unit6": "Bài 6: Du lịch & Địa điểm",
    "learning_path.in_progress": "Đang học",
    "learning_path.completed": "Hoàn thành",
    "learning_path.not_started": "Chưa bắt đầu",
    "learning_path.progress": "Tiến độ",
    "learning_path.learn_now": "Học ngay",
    "learning_path.materials": "Tài liệu",
    "learning_path.flashcards": "Thẻ ghi nhớ",
    "learning_path.speaking": "Luyện nói",
    "learning_path.review": "Ôn tập",
    "learning_path.locked": "Đã khóa",
    "dashboard.welcome": "Chào mừng trở lại, Minh Đức",
    "dashboard.subtitle": "Đây là những gì bạn cần làm hôm nay",
    "dashboard.streak_message": "Hãy duy trì chuỗi học và hoàn thành nhiệm vụ hàng ngày",
    "dashboard.learning_streak": "Chuỗi học tập",
    "dashboard.7_days": "7 Ngày",
    "dashboard.studied_7_days": "Bạn đã học 7 ngày liên tiếp",
    "dashboard.view_calendar": "Xem lịch",
    "dashboard.homework": "Bài tập về nhà",
    "dashboard.tasks_remaining": "Còn 2 nhiệm vụ",
    "dashboard.next_deadline": "Hạn chót tiếp theo:",
    "dashboard.continue": "Tiếp tục",
    "dashboard.ai_speaking": "Thực hành Nói AI",
    "dashboard.practice_now": "Thực hành ngay",
    "dashboard.current_rank": "Xếp hạng hiện tại",
    "dashboard.in_your_class": "trong lớp của bạn",
    "dashboard.view_leaderboard": "Xem bxh",
    "dashboard.todays_classes": "Lớp học hôm nay",
    "dashboard.schedule_date": "Lịch của bạn, Thứ Năm 26/03/2026",
    "dashboard.now": "Bây giờ",
    "dashboard.english": "Tiếng Anh",
    "dashboard.ms_thuthao": "Cô Thu Thảo • Phòng 5A",
    "dashboard.in_progress": "Đang diễn ra",
    "dashboard.todays_topic": "Chủ đề hôm nay",
    "dashboard.topic_en": "Bài 3: Giao tiếp hàng ngày - Luyện hội thoại",
    "dashboard.join_class": "Vào lớp",
    "dashboard.view_materials": "Xem tài liệu",
    "dashboard.next": "Sắp tới",
    "dashboard.math": "Toán học",
    "dashboard.mr_hoangnam": "Thầy Hoàng Nam • Phòng 5A",
    "dashboard.starts_15": "Bắt đầu trong 15 phút",
    "dashboard.topic_math": "Chương 5: Phân số - Cộng & Trừ",
    "dashboard.later": "Sau này",
    "dashboard.science": "Khoa học",
    "dashboard.ms_lananh": "Cô Lan Anh • Phòng thí nghiệm",
    "dashboard.after_lunch": "Sau bữa trưa",
    "dashboard.topic_sci": "Sinh học: Vòng đời thực vật",
    "dashboard.my_rank": "Xếp hạng của tôi",
    "dashboard.see_who": "Xem vị trí xếp hạng của bạn",
    "dashboard.you": "Minh Đức (Bạn)",
    "dashboard.todays_goals": "Mục tiêu hôm nay",
    "dashboard.goal1": "Hoàn thành bài tập",
    "dashboard.goal2": "Nói AI 10 phút",
    "dashboard.goal2_status": "Đã xong 5/10 phút",
    "dashboard.goal3": "Ôn 15 thẻ ghi nhớ",
    "auth.welcome": "Chào mừng trở lại",
    "auth.login_subtitle": "Đăng nhập để vào không gian EduLMS",
    "auth.username": "Tên đăng nhập",
    "auth.password": "Mật khẩu",
    "auth.remember": "Ghi nhớ đăng nhập",
    "auth.forgot": "Quên mật khẩu?",
    "auth.signin": "Đăng nhập",
    "auth.new_to": "Mới dùng EduLMS?",
    "auth.create_account": "Tạo tài khoản mới",
    "auth.create_title": "Tạo tài khoản",
    "auth.join_subtitle": "Tham gia EduLMS và trải nghiệm học tập thông minh",
    "auth.firstname": "Tên",
    "auth.lastname": "Họ",
    "auth.email": "Địa chỉ Email",
    "auth.registering": "Đăng ký thành công!",
    "auth.redirecting": "Đang chuyển đến trang đăng nhập...",
    "auth.signin_to": "Đăng nhập vào tài khoản",
    // ── Course Management ──
    "course.page_title": "Quản lý khóa học",
    "course.page_subtitle": "Tạo, quản lý và tổ chức các khóa học của bạn",
    "course.add_btn": "Thêm khóa học",
    "course.add_lesson": "Thêm bài học",
    "course.add_title": "Tạo khóa học mới",
    "course.add_subtitle": "Điền thông tin để tạo khóa học mới",
    "course.edit_title": "Sửa khóa học",
    "course.edit_subtitle": "Cập nhật thông tin khóa học",
    "course.name": "Tên khóa học",
    "course.name_placeholder": "VD: IELTS Foundation",
    "course.code": "Mã khóa học",
    "course.code_placeholder": "VD: IELTS-001",
    "course.level": "Trình độ",
    "course.start_date": "Ngày bắt đầu",
    "course.end_date": "Ngày kết thúc",
    "course.study_schedule": "Lịch học",
    "course.schedule_placeholder": "VD: Thứ 2, 4, 6 18:00-20:00",
    "course.max_attendants": "Số học sinh tối đa",
    "course.description": "Mô tả",
    "course.description_placeholder": "Nhập mô tả khóa học...",
    "course.status": "Trạng thái",
    "course.cancel": "Hủy",
    "course.create_btn": "Tạo khóa học",
    "course.save_btn": "Lưu thay đổi",
    "course.delete_btn": "Xóa",
    "course.assign_students": "Gán học sinh",
    "course.assign_teachers": "Gán giáo viên",
    "course.delete_title": "Xóa khóa học",
    "course.delete_warning": "Hành động này không thể hoàn tác",
    "course.delete_confirm": "Bạn có chắc chắn muốn xóa",
    "course.total_courses": "Tổng số khóa học",
    "course.active_courses": "Khóa học đang hoạt động",
    "course.draft_courses": "Khóa học nháp",
    "course.search_placeholder": "Tìm theo tên hoặc mã khóa học...",
    "course.no_courses": "Không tìm thấy khóa học nào",
    "course.no_courses_hint": "Nhấn 'Thêm khóa học' để tạo khóa học đầu tiên",
    "course.col_name": "Tên khóa học",
    "course.col_code": "Mã",
    "course.col_level": "Trình độ",
    "course.col_schedule": "Lịch học",
    "course.col_dates": "Thời gian",
    "course.col_capacity": "Sĩ số",
    "course.col_status": "Trạng thái",
    "course.col_actions": "Thao tác",
    "course.created_success": "Tạo khóa học thành công!",
    "course.updated_success": "Cập nhật khóa học thành công!",
    "course.deleted_success": "Xóa khóa học thành công!",
    "course.save_error": "Lỗi khi lưu khóa học. Vui lòng thử lại.",
    "course.delete_error": "Lỗi khi xóa khóa học. Vui lòng thử lại.",
    "course.error_name_required": "Tên khóa học không được để trống",
    "course.error_code_required": "Mã khóa học không được để trống",
    "course.error_start_required": "Ngày bắt đầu không được để trống",
    "course.error_end_required": "Ngày kết thúc không được để trống",
    "course.error_end_after_start": "Ngày kết thúc phải sau ngày bắt đầu",
    "course.error_schedule_required": "Lịch học không được để trống",
    "course.error_attendants_range": "Sĩ số phải từ 1 đến 500",
    "My Courses": "Khóa học của tôi",
    "Track your progress across all subjects": "Theo dõi tiến độ tất cả các môn",
    "Instructor": "Giáo viên",
    "lessons completed": "bài học đã hoàn thành",
    "Next": "Tiếp theo",
    "Course completed! Well done!": "Khóa học đã hoàn thành! Làm tốt lắm!",
    "Review Course": "Ôn tập khóa học",
    "View Certificate": "Xem chứng chỉ",
    "Continue Learning": "Tiếp tục học tập",
    "Course Details": "Chi tiết khóa học",
    "materials.page_title": "Tài liệu học tập",
    "materials.page_subtitle": "Tải lên, tạo và quản lý tài liệu học tập",
    "materials.total_materials": "Tổng số tài liệu",
    "materials.pdf_images": "PDF & Hình ảnh",
    "materials.flashcards": "Thẻ ghi nhớ",
    "materials.games": "Trò chơi học tập",
    "materials.upload_title": "Tải lên tệp",
    "materials.drop_hint": "Kéo thả tệp vào đây hoặc nhấp để tải lên",
    "materials.supported_formats": "Định dạng hỗ trợ: PDF, PNG, JPG, JPEG, DOC, DOCX, PPT, PPTX (Tối đa 50MB)",
    "materials.create_content": "Tạo nội dung học tập",
    "materials.create_material": "Tạo tài liệu khóa học",
    "materials.create_material_desc": "Tạo PDF, tài liệu hoặc bài thuyết trình cho khóa học",
    "materials.create_game": "Tạo trò chơi học tập",
    "materials.create_game_desc": "Thiết kế trò chơi tương tác để học tiếng Anh",
    "materials.create_flashcards_desc": "Xây dựng bộ thẻ ghi nhớ để luyện từ vựng",
    "materials.library_title": "Thư viện tài liệu",
    "materials.library_subtitle": "Quản lý tất cả tài liệu học tập của bạn",
    "materials.search_placeholder": "Tìm kiếm tài liệu...",
    "materials.col_name": "Tên tài liệu",
    "materials.col_type": "Loại",
    "materials.col_course": "Khóa học",
    "materials.col_created_by": "Người tạo",
    "materials.col_last_updated": "Cập nhật lần cuối",
    "materials.col_status": "Trạng thái",
    "materials.col_downloads": "Lượt tải",
    "materials.col_actions": "Thao tác",
    "materials.upload_success": "Tải lên tài liệu thành công!",
    "materials.delete_success": "Xóa tài liệu thành công!",
    "materials.upload_confirm": "Bạn có chắc chắn muốn tải lên các tài liệu này?",
    "materials.delete_confirm": "Bạn có chắc chắn muốn xóa tài liệu này?",
    "materials.no_materials": "Không tìm thấy tài liệu nào",
    "materials.category": "Danh mục",
    "materials.general": "Chung",
    "materials.flashcard": "Thẻ ghi nhớ",
    "materials.game": "Trò chơi tiếng Anh",
    "materials.preview_mode": "Chế độ xem trước",
    "materials.preview_unavailable": "Không thể xem trước",
    "materials.preview_unavailable_desc": "Loại tệp này không thể xem trước trực tiếp trên trình duyệt. Vui lòng tải xuống để xem nội dung.",
    "materials.all_types": "Tất cả loại",
    "materials.all_status": "Tất cả trạng thái",
    "materials.published": "Đã đăng",
    "materials.draft": "Bản nháp",
    "flashcard.review_subtitle": "Ôn tập từ vựng và chơi trò chơi học tập",
    "flashcard.card": "Thẻ",
    "flashcard.complete": "Hoàn thành",
    "flashcard.flip": "Lật thẻ",
    "flashcard.no_data": "Chưa có thẻ ghi nhớ nào.",
    "games.title": "Trò chơi học tập",
    "games.match_title": "Ghép từ",
    "games.match_desc": "Ghép từ với ý nghĩa của chúng",
    "games.image_title": "Chọn hình ảnh",
    "games.image_desc": "Chọn đúng hình ảnh cho mỗi từ",
    "games.spell_title": "Đánh vần từ",
    "games.spell_desc": "Kiểm tra kỹ năng đánh vần",
    "flashcard.management_title": "Từ vựng",
    "flashcard.management_subtitle": "Quản lý thẻ từ vựng và phiên âm IPA",
    "flashcard.add_btn": "Thêm từ vựng",
    "flashcard.edit_btn": "Sửa từ vựng",
    "flashcard.total_words": "Tổng số từ",
    "flashcard.word": "Từ vựng",
    "flashcard.ipa": "Phiên âm (IPA)",
    "flashcard.definition": "Định nghĩa/Ý nghĩa",
    "flashcard.example": "Câu ví dụ",
    "flashcard.created_success": "Đã lưu từ vựng thành công!",
    "flashcard.deleted_success": "Đã xóa từ vựng thành công!",
    "flashcard.delete_confirm": "Bạn có chắc chắn muốn xóa từ vựng này không?",
    "flashcard.topic": "Chủ đề",
    "flashcard.topic_placeholder": "VD: Động vật, Đồ ăn...",
    "flashcard.image": "Hình ảnh (Tùy chọn)",
    "flashcard.upload_image": "Tải ảnh lên",
    "flashcard.image_url_placeholder": "Hoặc dán URL hình ảnh vào đây...",
    "flashcard.uploading": "Đang tải lên...",
    "flashcard.all_topics": "Tất cả chủ đề",
    "flashcard.sync_ai": "Đồng bộ AI",
    "flashcard.syncing_ai": "Đang đồng bộ...",
    "flashcard.sync_success": "Đã đồng bộ từ vựng với Dịch vụ AI thành công",
    "flashcard.sync_error": "Lỗi khi đồng bộ từ vựng với AI",
    "games.scramble_title": "Sắp xếp từ",
    "games.scramble_difficulty": "Dễ",
    "games.scramble_desc": "Sắp xếp lại các chữ cái để tìm từ vựng đúng. Tuyệt vời để luyện đánh vần!",
    "games.sentence_title": "Bậc thầy Câu cú",
    "games.sentence_desc": "Sắp xếp các từ bị xáo trộn thành một câu hoàn chỉnh. Thử thách ngữ pháp cực vui!",
    "games.memory_title": "Ghép đôi trí nhớ",
    "games.memory_desc": "Lật thẻ để tìm các cặp từ và định nghĩa hoặc hình ảnh tương ứng.",
    "games.listen_title": "Nghe & Gõ",
    "games.listen_desc": "Nghe phát âm của từ và gõ lại chính xác cùng với phiên âm IPA.",
    "games.translation_title": "Bậc thầy Dịch thuật",
    "games.translation_desc": "Chọn bản dịch chính xác cho từ đã cho. Kiểm tra vốn từ vựng của bạn bằng cả tiếng Anh và tiếng Việt!",
    "games.translation_difficulty": "Trung bình",
    "games.translate_to_vn": "Dịch sang tiếng Việt",
    "games.translate_to_en": "Dịch sang tiếng Anh",
    "games.play_now": "Chơi ngay",
    "games.coming_soon": "Sắp ra mắt",
    "games.back": "Quay lại",
    "games.scrambled_word": "Từ bị xáo trộn",
    "games.hint_label": "GỢI Ý / Ý NGHĨA",
    "games.input_placeholder": "Nhập câu trả lời của bạn...",
    "games.verify_btn": "Kiểm tra",
    "games.correct": "Chính xác!",
    "games.wrong": "Sai rồi, thử lại nhé!",
    "games.congrats": "Chúc mừng! Bạn đã hoàn thành trò chơi!",
    "games.roadmap_step1_title": "Lấy nội dung",
    "games.roadmap_step1_desc": "Sử dụng API /api/games/scramble để lấy các thử thách động.",
    "games.roadmap_step2_title": "Xác minh trực tiếp",
    "games.roadmap_step2_desc": "Gửi câu trả lời để kiểm tra ngay lập tức phía máy chủ.",
    "games.roadmap_step3_title": "Phần thưởng tương lai",
    "games.roadmap_step3_desc": "Sắp tới: Nhận xu và XP để mở khóa các thành tích độc quyền!",
    "games.daily_title": "Thử thách Bí mật",
    "games.daily_subtitle": "Một thử thách kỳ bí đang chờ bạn...",
    "games.daily_desc": "Hoàn thành nhiệm vụ hôm nay để nhận thêm xu và XP. Thử thách mới sau mỗi 24 giờ!",
    "games.daily_claimed": "Đã hoàn thành",
    "games.daily_difficulty": "BÍ MẬT",
    "games.rewards_title": "Phần thưởng nhận được",
    "games.xp": "XP",
    "games.coins": "Xu",
    "course.start_time": "Thời gian bắt đầu",
    "course.end_time": "Thời gian kết thúc",
    "course.error_teacher_required_for_active": "Phải phân công giáo viên trước khi kích hoạt khóa học",
    "course.exam_zone": "Khu vực Kiểm tra & Thi",
    "course.exam_zone_desc": "Các bài đánh giá và kiểm tra trình độ",
    "course.create_test": "Tạo bài kiểm tra",
    "course.manage_test": "Quản lý bài kiểm tra",
    "course.do_test": "Làm bài kiểm tra",
    "course.no_exams": "Chưa có bài kiểm tra nào được lên lịch cho khóa học này.",
    "test.title": "Tiêu đề bài kiểm tra",
    "test.time_limit": "Giới hạn thời gian (Phút)",
    "test.pass_score": "Điểm đạt (%)",
    "test.total_score": "Tổng điểm",
    "test.description": "Mô tả (Tùy chọn)",
    "test.questions": "Câu hỏi",
    "test.add_question": "Thêm câu hỏi",
    "video.interactive_question": "Kiểm tra kiến thức",
    "video.type_answer": "Nhập câu trả lời của bạn...",
    "video.correct": "Chính xác! Rất tốt.",
    "video.incorrect": "Sai rồi. Vui lòng thử lại!",
    "video.submit": "Gửi câu trả lời",
    "video.continue": "Tiếp tục Video",
    "video.tab": "Video tương tác",
    "ai_learning.title": "Trung tâm Học AI",
    "ai_learning.subtitle": "Chọn một mô-đun để rèn luyện kỹ năng tiếng Anh",
    "ai_learning.speaking": "Luyện Nói",
    "ai_learning.speaking_desc": "Luyện giao tiếp tiếng Anh với AI",
    "ai_learning.writing": "Luyện Viết",
    "ai_learning.writing_desc": "Cải thiện kỹ năng viết và ngữ pháp",
    "ai_learning.choose_friend": "Chọn người bạn AI",
    "ai_learning.start": "Bắt đầu Luyện tập",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("app_lang") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "vi")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
