import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "menu.home": "Home",
    "menu.dashboard": "Dashboard",
    "menu.courses": "Courses",
    "menu.my_courses": "My Courses",
    "menu.students": "Students",
    "menu.student_management": "Student Management",
    "menu.attendance": "Attendance",
    "menu.user_management": "User Management",
    "menu.learning_materials": "Learning Materials",
    "menu.reports": "Reports",
    "menu.settings": "Settings",
    "menu.learning_path": "Learning Path",
    "menu.ai_speaking": "AI Speaking",
    "menu.flashcards": "Flashcards",
    "menu.achievements": "Achievements",
    "search.placeholder": "Search...",
    "header.logout": "Logout",
    "learning_path.subtitle": "Continue your lessons and track your progress",
    "learning_path.unit1": "Unit 1: Greetings & Introductions",
    "learning_path.unit2": "Unit 2: Family & Friends",
    "learning_path.unit3": "Unit 3: Daily Conversations",
    "learning_path.unit4": "Unit 4: Hobbies & Activities",
    "learning_path.unit5": "Unit 5: Food & Restaurants",
    "learning_path.unit6": "Unit 6: Travel & Places",
    "learning_path.in_progress": "In Progress",
    "learning_path.completed": "Completed",
    "learning_path.not_started": "Not Started",
    "learning_path.progress": "Progress",
    "learning_path.learn_now": "Learn Now",
    "learning_path.materials": "Materials",
    "learning_path.flashcards": "Flashcards",
    "learning_path.speaking": "Speaking",
    "learning_path.review": "Review",
    "learning_path.locked": "Locked",
    "dashboard.welcome": "Welcome back, Minh Duc",
    "dashboard.subtitle": "Here's what you need to do today",
    "dashboard.streak_message": "Keep your streak going and complete your daily missions",
    "dashboard.learning_streak": "Learning Streak",
    "dashboard.7_days": "7 Days",
    "dashboard.studied_7_days": "You've studied 7 days in a row",
    "dashboard.view_calendar": "View Calendar",
    "dashboard.homework": "Homework",
    "dashboard.tasks_remaining": "2 tasks remaining",
    "dashboard.next_deadline": "Next deadline:",
    "dashboard.continue": "Continue",
    "dashboard.ai_speaking": "AI Speaking Practice",
    "dashboard.practice_now": "Practice Now",
    "dashboard.current_rank": "Current Rank",
    "dashboard.in_your_class": "in your class",
    "dashboard.view_leaderboard": "View Leaderboard",
    "dashboard.todays_classes": "Today's Classes",
    "dashboard.schedule_date": "Your schedule for Thursday, March 26, 2026",
    "dashboard.now": "Now",
    "dashboard.english": "English Language",
    "dashboard.ms_thuthao": "Ms. Thu Thao • Room 5A",
    "dashboard.in_progress": "In Progress",
    "dashboard.todays_topic": "Today's Topic",
    "dashboard.topic_en": "Unit 3: Daily Conversations - Practice Dialogues",
    "dashboard.join_class": "Join Class",
    "dashboard.view_materials": "View Materials",
    "dashboard.next": "Next",
    "dashboard.math": "Mathematics",
    "dashboard.mr_hoangnam": "Mr. Hoang Nam • Room 5A",
    "dashboard.starts_15": "Starts in 15 min",
    "dashboard.topic_math": "Chapter 5: Fractions - Adding & Subtracting",
    "dashboard.later": "Later",
    "dashboard.science": "Science",
    "dashboard.ms_lananh": "Ms. Lan Anh • Science Lab",
    "dashboard.after_lunch": "After lunch",
    "dashboard.topic_sci": "Biology: Plant Life Cycles - Lab Activity",
    "dashboard.my_rank": "My Rank",
    "dashboard.see_who": "See who is just above and below you",
    "dashboard.you": "Minh Duc (You)",
    "dashboard.todays_goals": "Today's Goals",
    "dashboard.goal1": "Finish homework",
    "dashboard.goal2": "Practice AI speaking for 10 minutes",
    "dashboard.goal2_status": "5/10 minutes completed",
    "dashboard.goal3": "Review 15 flashcards",
    "auth.welcome": "Welcome Back",
    "auth.login_subtitle": "Sign in to access your EduLMS workspace",
    "auth.username": "Username",
    "auth.password": "Password",
    "auth.remember": "Remember me",
    "auth.forgot": "Forgot your password?",
    "auth.signin": "Sign In",
    "auth.new_to": "New to EduLMS?",
    "auth.create_account": "Create an account",
    "auth.create_title": "Create your account",
    "auth.join_subtitle": "Join EduLMS and experience smart learning",
    "auth.firstname": "First name",
    "auth.lastname": "Last name",
    "auth.email": "Email address",
    "auth.registering": "Registration Successful!",
    "auth.redirecting": "Redirecting to login...",
    "auth.already_have": "Already have an account?",
    "auth.signin_to": "Sign in to your account",
    "Create System Account": "Create System Account",
    "Create Student Account": "Create Student Account",
  },
  vi: {
    "menu.home": "Trang chủ",
    "menu.dashboard": "Bảng điều khiển",
    "menu.courses": "Khóa học",
    "menu.my_courses": "Khóa học của tôi",
    "menu.students": "Học sinh",
    "menu.student_management": "Quản lý học sinh",
    "menu.attendance": "Điểm danh",
    "menu.user_management": "Quản lý người dùng",
    "menu.learning_materials": "Tài liệu học tập",
    "menu.reports": "Báo cáo",
    "menu.settings": "Cài đặt",
    "menu.learning_path": "Lộ trình học tập",
    "menu.ai_speaking": "Luyện nói AI",
    "menu.flashcards": "Thẻ ghi nhớ",
    "menu.achievements": "Thành tích",
    "search.placeholder": "Tìm kiếm...",
    "header.logout": "Đăng xuất",
    "learning_path.subtitle": "Tiếp tục bài học và theo dõi tiến độ của bạn",
    "learning_path.unit1": "Bài 1: Chào hỏi & Giới thiệu",
    "learning_path.unit2": "Bài 2: Gia đình & Bạn bè",
    "learning_path.unit3": "Bài 3: Hội thoại hàng ngày",
    "learning_path.unit4": "Bài 4: Sở thích & Hoạt động",
    "learning_path.unit5": "Bài 5: Ẩm thực & Nhà hàng",
    "learning_path.unit6": "Bài 6: Du lịch & Địa điểm",
    "learning_path.in_progress": "Đang học",
    "learning_path.completed": "Hoàn thành",
    "learning_path.not_started": "Chưa bắt đầu",
    "learning_path.progress": "Tiến độ",
    "learning_path.learn_now": "Học ngay",
    "learning_path.materials": "Tài liệu",
    "learning_path.flashcards": "Thẻ ghi nhớ",
    "learning_path.speaking": "Luyện nói",
    "learning_path.review": "Ôn tập",
    "learning_path.locked": "Đã khóa",
    "dashboard.welcome": "Chào mừng trở lại, Minh Đức",
    "dashboard.subtitle": "Đây là những gì bạn cần làm hôm nay",
    "dashboard.streak_message": "Hãy duy trì chuỗi học và hoàn thành nhiệm vụ hàng ngày",
    "dashboard.learning_streak": "Chuỗi học tập",
    "dashboard.7_days": "7 Ngày",
    "dashboard.studied_7_days": "Bạn đã học 7 ngày liên tiếp",
    "dashboard.view_calendar": "Xem lịch",
    "dashboard.homework": "Bài tập về nhà",
    "dashboard.tasks_remaining": "Còn 2 nhiệm vụ",
    "dashboard.next_deadline": "Hạn chót tiếp theo:",
    "dashboard.continue": "Tiếp tục",
    "dashboard.ai_speaking": "Thực hành Nói AI",
    "dashboard.practice_now": "Thực hành ngay",
    "dashboard.current_rank": "Xếp hạng hiện tại",
    "dashboard.in_your_class": "trong lớp của bạn",
    "dashboard.view_leaderboard": "Xem bxh",
    "dashboard.todays_classes": "Lớp học hôm nay",
    "dashboard.schedule_date": "Lịch của bạn, Thứ Năm 26/03/2026",
    "dashboard.now": "Bây giờ",
    "dashboard.english": "Tiếng Anh",
    "dashboard.ms_thuthao": "Cô Thu Thảo • Phòng 5A",
    "dashboard.in_progress": "Đang diễn ra",
    "dashboard.todays_topic": "Chủ đề hôm nay",
    "dashboard.topic_en": "Bài 3: Giao tiếp hàng ngày - Luyện hội thoại",
    "dashboard.join_class": "Vào lớp",
    "dashboard.view_materials": "Xem tài liệu",
    "dashboard.next": "Sắp tới",
    "dashboard.math": "Toán học",
    "dashboard.mr_hoangnam": "Thầy Hoàng Nam • Phòng 5A",
    "dashboard.starts_15": "Bắt đầu trong 15 phút",
    "dashboard.topic_math": "Chương 5: Phân số - Cộng & Trừ",
    "dashboard.later": "Sau này",
    "dashboard.science": "Khoa học",
    "dashboard.ms_lananh": "Cô Lan Anh • Phòng thí nghiệm",
    "dashboard.after_lunch": "Sau bữa trưa",
    "dashboard.topic_sci": "Sinh học: Vòng đời thực vật",
    "dashboard.my_rank": "Xếp hạng của tôi",
    "dashboard.see_who": "Xem vị trí xếp hạng của bạn",
    "dashboard.you": "Minh Đức (Bạn)",
    "dashboard.todays_goals": "Mục tiêu hôm nay",
    "dashboard.goal1": "Hoàn thành bài tập",
    "dashboard.goal2": "Nói AI 10 phút",
    "dashboard.goal2_status": "Đã xong 5/10 phút",
    "dashboard.goal3": "Ôn 15 thẻ ghi nhớ",
    "auth.welcome": "Chào mừng trở lại",
    "auth.login_subtitle": "Đăng nhập để vào không gian EduLMS",
    "auth.username": "Tên đăng nhập",
    "auth.password": "Mật khẩu",
    "auth.remember": "Ghi nhớ đăng nhập",
    "auth.forgot": "Quên mật khẩu?",
    "auth.signin": "Đăng nhập",
    "auth.new_to": "Mới dùng EduLMS?",
    "auth.create_account": "Tạo tài khoản mới",
    "auth.create_title": "Tạo tài khoản",
    "auth.join_subtitle": "Tham gia EduLMS và trải nghiệm học tập thông minh",
    "auth.firstname": "Tên",
    "auth.lastname": "Họ",
    "auth.email": "Địa chỉ Email",
    "auth.registering": "Đăng ký thành công!",
    "auth.redirecting": "Đang chuyển đến trang đăng nhập...",
    "auth.already_have": "Đã có tài khoản?",
    "auth.signin_to": "Đăng nhập vào tài khoản",
    "My Courses": "Khóa học của tôi",
    "Track your progress across all subjects": "Theo dõi tiến độ tất cả các môn",
    "Instructor": "Giáo viên",
    "lessons completed": "bài học đã hoàn thành",
    "Next": "Tiếp theo",
    "Course completed! Well done!": "Khóa học đã hoàn thành! Làm tốt lắm!",
    "Review Course": "Ôn tập khóa học",
    "View Certificate": "Xem chứng chỉ",
    "Continue Learning": "Tiếp tục học tập",
    "Course Details": "Chi tiết khóa học",
    "Level 5": "Cấp độ 5",
    "Math Fundamentals": "Toán học cơ bản",
    "Science Explorer": "Khám phá khoa học",
    "AI Speaking Coach": "Huấn luyện viên AI Luyện nói",
    "Ready to help": "Sẵn sàng giúp đỡ",
    "Hello! I'm your AI speaking coach. Today we'll practice family and school vocabulary. Are you ready?": "Xin chào! Tôi là HLV AI của bạn. Hôm nay chúng ta sẽ luyện tập từ vựng gia đình và trường học. Sẵn sàng chưa?",
    "Yes, I'm ready!": "Vâng, tôi đã sẵn sàng!",
    "Great! Let's start with the word 'Hello'. Try to say it clearly.": "Tuyệt vời! Bắt đầu với từ 'Hello'. Hãy cố gắng nói thật rõ nhé.",
    "Hello": "Hello",
    "Excellent pronunciation! ✨ Now let's try 'Family'.": "Phát âm xuất sắc! ✨ Bây giờ hãy thử 'Family'.",
    "Press the microphone to start speaking": "Nhấn micro để bắt đầu nói",
    "Recording... Say the target word clearly": "Đang ghi âm... Hãy nói rõ từ khóa",
    "Target Words": "Từ khóa mục tiêu",
    "Practice these vocabulary words": "Luyện tập những từ vựng này",
    "Session Progress": "Tiến độ buổi học",
    "words completed": "từ đã hoàn thành",
    "Card": "Thẻ",
    "Complete": "Hoàn thành",
    "Click to flip": "Nhấn để lật",
    "Meaning": "Ý nghĩa",
    "A group of people related by blood or marriage": "Một nhóm người có quan hệ huyết thống hoặc hôn nhân",
    "I love spending time with my family.": "Tôi thích dành thời gian cho gia đình.",
    "A person you know well and like": "Người mà bạn biết rõ và quý mến",
    "She is my best friend.": "Cô ấy là bạn thân của tôi.",
    "A place where children go to learn": "Nơi trẻ em đến để học",
    "I go to school every day.": "Tôi đến trường mỗi ngày.",
    "Example": "Ví dụ",
    "Flip Card": "Lật thẻ",
    "Listen": "Nghe",
    "Learning Games": "Trò chơi học tập",
    "Match the Word": "Ghép từ",
    "Match words with their meanings": "Ghép từ với ý nghĩa của chúng",
    "Choose the Image": "Chọn hình ảnh",
    "Pick the correct image for each word": "Chọn đúng hình ảnh cho mỗi từ",
    "Spell the Word": "Đánh vần từ",
    "Test your spelling skills": "Kiểm tra kỹ năng đánh vần",
    "Current": "Hiện tại",
    "Days": "Ngày",
    "Total": "Tổng",
    "Points Earned": "Điểm đạt được",
    "Unlocked": "Đã mở khóa",
    "Badges": "Huy hiệu",
    "Class": "Lớp",
    "Your Rank": "Hạng của bạn",
    "Track your badges, streaks, and milestones": "Theo dõi huy hiệu, chuỗi và cột mốc",
    "Level Progress": "Tiến độ Cấp độ",
    "Keep learning to reach the next level": "Tiếp tục học để đạt cấp độ tiếp theo",
    "until Level 6": "nữa để đến Cấp độ 6",
    "This Week's Performance": "Hiệu suất tuần này",
    "You're doing great! Keep it up!": "Bạn đang làm rất tốt! Hãy duy trì!",
    "Badge Collection": "Bộ sưu tập huy hiệu",
    "3-Day Streak": "Chuỗi 3 ngày",
    "7-Day Streak": "Chuỗi 7 ngày",
    "Homework Hero": "Siêu nhân Bài tập",
    "Speaking Star": "Ngôi sao Giao tiếp",
    "Vocabulary Master": "Bậc thầy Từ vựng",
    "14-Day Streak": "Chuỗi 14 ngày",
    "Quiz Champion": "Nhà vô địch Trắc nghiệm",
    "Perfect Score": "Điểm tuyệt đối",
    "Recent Milestones": "Cột mốc gần đây",
    "Completed Unit 2": "Đã hoàn thành Bài 2",
    "Earned": "Đạt được",
    "7-Day Streak Achieved": "Đạt Chuỗi 7 Ngày",
    "Unlocked Badge": "Đã mở khóa huy hiệu",
    "All Homework Completed": "Hoàn thành mọi Bài tập",
    "Reached Level 5": "Đạt Cấp độ 5",
    "New abilities unlocked": "Khả năng mới được mở khóa",
    "Courses Component": "Khóa học",
    "Manage your courses and curriculum": "Quản lý khóa học và chương trình giảng dạy",
    "Mathematics": "Toán học",
    "Science": "Khoa học",
    "English": "Tiếng Anh",
    "History": "Lịch sử",
    "Students_Label": "Học sinh",
    "Active": "Đang hoạt động",
    "Administer platform roles and student onboarding": "Quản trị vai trò hệ thống và thông tin học sinh",
    "System Users": "Người dùng hệ thống",
    "Students": "Học sinh",
    "Enter full name": "Nhập họ và tên",
    "Temporary Password": "Mật khẩu tạm thời",
    "Set temporary password": "Đặt mật khẩu tạm",
    "System": "Hệ thống",
    "Student": "Học sinh",
    "Account": "Tài khoản",
    "Create": "Tạo mới",
    "Create System Account": "Tạo mới tài khoản hệ thống",
    "Create Student Account": "Tạo mới tài khoản học sinh",
    "User will be prompted to change this temporary password on their first login.": "Người dùng sẽ được yêu cầu đổi mật khẩu tạm thời trong lần đăng nhập đầu tiên.",
    "Manage and organize student information": "Quản lý và tổ chức thông tin học sinh",
    "Import": "Nhập dữ liệu",
    "Export": "Xuất dữ liệu",
    "Add Student": "Thêm một học sinh",
    "Total Students_Stat": "Tổng số học sinh",
    "Active Students": "Đang hoạt động",
    "Filter": "Lọc",
    "Sort": "Sắp xếp",
    "No students found": "Không tìm thấy học sinh nào",
    "Theme Settings": "Cài đặt giao diện",
    "Customize the appearance of your dashboard": "Tùy chỉnh giao diện bảng điều khiển của bạn",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("app_lang") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "vi")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
